name: rpm
on:
  push:
    tags:
      - "*rpm*"
jobs:
  rpm_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: build_package
        run: |
          cd solver_application
          cmake -DCPACK_GENERETOR_RPM=ON -B ./build
          cd build
          make package
          make package_source
          ls
          pwd
      - name: create release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: solver_application/build/equation-0.1.1-Linux.rpm
          asset_name: equation-0.1.1-Linux.rpm
          asset_content_type: application/rpm